const ACTIONS = {
  JOIN: "JOIN",
  NEWUSERJOINED: "NEWUSERJOINED",
  DISCONNECTED: "DISCONNECTED",
  LEAVE: "LEAVE",
  "OBJECT:MOVING": "OBJECT:MOVING",
  "OBJECT:SCALING": "OBJECT:SCALING",
  "OBJECT:ROTATING": "OBJECT:ROTATING",
  "OBJECT:REMOVED": "OBJECT:REMOVED",
  "OBJECT:CHANGED": "OBJECT:CHANGED",
  "OBJECT:ADDED": "OBJECT:ADDED",
  "TEXT:CHANGED": "TEXT:CHANGED",

  "STOKEWIDTH:CHANGED": "STOKEWIDTH:CHANGED",
  "STOKE:CHANGED": "STOKE:CHANGED",
  "FILL:CHANGED": "FILL:CHANGED",
  "STROKESTYLE:CHANGED": "STROKESTYLE:CHANGED",
  "OPACITY:CHANGED": "OPACITY:CHANGED",
  SENDTOBACK: "SENDTOBACK",
  SENDBACKWARD: "SENDBACKWARD",
  BRINGTOFRONT: "BRINGTOFRONT",
  BRINGFORWARD: "BRINGFORWARD",
};

export { ACTIONS };
